### ISSUE TITLE
PCM on docker container solution without privileged 

### ISSUE THREAD

**Issue by mRSun15** [opcm/pcm#203]
I learned that in your instruction when we run the pcm on docker container, we need to run in privileged mode, however, running a container in privileged mode is not a good choice actually. Can you provide some alternative solution to run the PCM on docker container?

**Comment by opcm** [comment]
we will look into your request on what is possible

**Comment by opcm** [comment]
@mRSun15 with some changes in pcm the best we could come up with is running with `--cap-add=SYS_ADMIN --cap-add=SYS_RAWIO --device=/dev/cpu:/dev/cpu -v /sys/firmware/acpi/tables/MCFG:/pcm/sys/firmware/acpi/tables/MCFG:ro -v /proc/bus/pci/:/pcm/proc/bus/pci/` instead of `--privileged`.

should we implement these changes?

**Comment by mRSun15** [comment]
@opcm Yes, I think it would be better to add these implementations. It's obvious that if we run the container in privileged mode, it will be dangerous with unlimited capabilities. It's more appropriate if the limited capabilities granted to the container.
