### ISSUE TITLE
pcm-sensor-server closes connection when unknown HTTP headers are present

### ISSUE THREAD

**Issue by tnn2** [opcm/pcm#261]
Hello,

We are running `pcm-sensor-server` behind a reverse proxy that sets some non-standard diagnostic headers on the request.
This causes the server to unexpectedly fail:
```
# curl --header "x-foo: bar" http://localhost:9738/metrics
curl: (52) Empty reply from server
```
From the log we can see:
```
DBG(3): virtual void HTTPConnection::execute():
DBG(3): Reading request from socket: Exception caught: headerType: Headername not found
```

I think it would make sense to (as most webservers tend to) silently ignore unknown headers instead of failing the request.

**Comment by opcm** [comment]
@tnn2  thanks for reporting this issue. While we are considering a cleaner solution could you please try this quick workaround?

https://github.com/opcm/pcm/tree/opcm-ignore-unknown-headers-workaround

**Comment by ogbrugge** [comment]
That would have been the approach I would take on Thursday when I will be back in the office, not sure why I missed this obvious lack of custom header processing... possibly because I am not sure if any of these customs headers are expected to be returned back to the client. I need to read the http spec again about what is expected.

**Comment by opcm** [comment]
this should be addressed in thi merge to master: https://github.com/opcm/pcm/commit/0a178ec2573821e3c08beb6bd76808ebb912bc76
