### ISSUE TITLE
Add absolute timestamp to csv output

### ISSUE THREAD

**Issue by patinnc** [opcm/pcm#80]
Hello,
I'm adding support for PCM to OPPAT (https://patinnc.github.io/) but I need to be able to correlate the pcm csv data with other data. In particular with higher resolution than 1 second. This would let me correlate the PCM data with ETW or ftrace data.
I would like to add an absolute timestamp such as in the attached patch. It uses GetSystemTimeAsFileTime on windows, clock_gettime(CLOCK_MONOTONIC, &tp) on linux. I'm not sure what to do on FreeBSD or Mac.
Thanks
Pat

[pcm_20181006_patch.txt](https://github.com/opcm/pcm/files/2452738/pcm_20181006_patch.txt)

**Comment by opcm** [comment]
Pat, 

thank you for sending the patch.

Unfortunately it is unclear to me if we can include this change into PCM since it includes some code from stackoverflow authored by a different person where the copyright and license is unclear. Also patch submission should be done via a pull request. Could you please rewrite the patch yourself and submit it via a pull request?

Thanks,
Roman

**Comment by opcm** [comment]
Pat,

You don't need any permission to create a pull request. You can fork PCM and then create a pull request to the upstream PCM repository:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks,
Roman

**Comment by opcm** [comment]
Pat, you are right. I adding a request to add such option in the PR
